config:
        mainpage: My Main Page
        space-prefix:
                ABC: "MY_NAMESPACE:ABC/"
                DEF: "MY_NAMESPACE:DEf/"
                GHI: "GHI_NAMESPACE:"
        composer-skip-namespace:
          - ABC
        composer-skip-titles:
          - ABC:DEF/GHI
        categories:
                - My Category 1
                - My Category 2
        ext-ns-file-repo-compat: true
        include-history: false,
        composer-page-per-xml-limit: 100,
        ns-talk-suffix: Talk
